import{CONFIG}from"./config.js";
import{initializeApp}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import{getAuth,signInAnonymously,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import{getDatabase,ref,get,set,push,update,remove,runTransaction}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-database.js";
import{getStorage,ref as storageRef,uploadBytes,getDownloadURL}from"https://www.gstatic.com/firebasejs/12.16.0/firebase-storage.js";

const firebaseApp=initializeApp(CONFIG.firebase),auth=getAuth(firebaseApp),db=getDatabase(firebaseApp),storage=getStorage(firebaseApp),$=selector=>document.querySelector(selector);
const countries=[["الكويت","+965","🇰🇼"],["الهند","+91","🇮🇳"],["مصر","+20","🇪🇬"],["الفلبين","+63","🇵🇭"],["بنغلاديش","+880","🇧🇩"],["سوريا","+963","🇸🇾"],["الأردن","+962","🇯🇴"],["فلسطين","+970","🇵🇸"],["لبنان","+961","🇱🇧"]];
let employee=null,currentPin="",publishedSchedules=[];
const digits=(value="")=>String(value).replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d)).replace(/[۰-۹]/g,d=>"۰۱۲۳۴۵۶۷۸۹".indexOf(d));
const onlyDigits=value=>digits(value).replace(/\D/g,"");
const esc=(value="")=>String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const firstName=name=>String(name||"موظف").trim().split(/\s+/)[0];
const initials=name=>String(name||"").trim().split(/\s+/).slice(0,2).map(x=>x[0]||"").join("");
const dateKey=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const formatTime=value=>{const[h,m]=value.split(":").map(Number),period=h>=12?"م":"ص",hour=h%12||12;return`${hour}:${String(m).padStart(2,"0")} ${period}`;};
const dialOptions=selected=>countries.map(country=>`<option value="${country[1]}" ${country[1]===selected?"selected":""}>${country[2]} ${country[1]} · ${country[0]}</option>`).join("");
const phoneField=(number,dial,index,type)=>`<div class="settings-phone-row"><select name="${type}Dial">${dialOptions(dial||"+965")}</select><input name="${type}Phone" value="${esc(number||"")}" inputmode="numeric" maxlength="15" placeholder="رقم الهاتف">${type==="alternate"?`<button type="button" data-remove-phone="${type}:${index}">×</button>`:"<span></span>"}</div>`;

function showPinPage(message=""){$("#boot").classList.add("hidden");$("#employee-app").classList.add("hidden");$("#pin-page").classList.remove("hidden");$("#pin-message").textContent=message;}
function showToast(message){const toast=$("#portal-toast");toast.textContent=message;toast.classList.remove("hidden");setTimeout(()=>toast.classList.add("hidden"),3500);}
function loading(show,title="يرجى الانتظار",text="يتم حفظ بياناتك..."){const el=$("#portal-loading");el.classList.toggle("hidden",!show);el.querySelector("h3").textContent=title;el.querySelector("p").textContent=text;}
function bindNumeric(root=document){root.querySelectorAll('input[inputmode="numeric"]').forEach(input=>input.oninput=()=>input.value=onlyDigits(input.value));}

async function start(){try{await signInAnonymously(auth);}catch(error){showPinPage("فعّل تسجيل الدخول المجهول Anonymous في Firebase Authentication ثم أعد المحاولة.");}}
onAuthStateChanged(auth,user=>{if(!user)return;const saved=sessionStorage.getItem("rakaezEmployeePin");if(saved){$("#pin-code").value=saved;loginWithPin(saved);}else showPinPage();});

$("#pin-form").onsubmit=event=>{event.preventDefault();loginWithPin($("#pin-code").value);};bindNumeric($("#pin-form"));
async function loginWithPin(rawPin){const pin=onlyDigits(rawPin),message=$("#pin-message");if(pin.length<4){message.textContent="أدخل رمزًا صحيحًا.";return;}message.textContent="جاري التحقق...";try{const pinSnap=await get(ref(db,`organizations/default/attendancePins/${pin}`));if(!pinSnap.exists())throw new Error("رمز الدخول غير صحيح.");const employeeSnap=await get(ref(db,`organizations/default/employees/${pinSnap.val()}`));if(!employeeSnap.exists())throw new Error("لم يتم العثور على ملف الموظف.");employee={id:employeeSnap.key,...employeeSnap.val()};currentPin=pin;sessionStorage.setItem("rakaezEmployeePin",pin);await loadSchedules();renderHome();}catch(error){message.textContent=error.message;}}
async function loadSchedules(){const snap=await get(ref(db,"organizations/default/schedules")),value=snap.val()||{};publishedSchedules=Object.values(value).filter(item=>item.published).sort((a,b)=>String(a.dateKey).localeCompare(String(b.dateKey)));}

function employeeAssignments(){const today=dateKey(new Date()),todaySchedule=publishedSchedules.find(item=>item.dateKey===today),nextSchedule=publishedSchedules.find(item=>item.dateKey>=today)||publishedSchedules.at(-1),selected=todaySchedule||nextSchedule;if(!selected)return{schedule:null,items:[]};return{schedule:selected,items:Object.values(selected.assignments||{}).filter(item=>item.employeeId===employee.id)};}
function renderHome(){const{schedule,items}=employeeAssignments();$("#pin-page").classList.add("hidden");$("#boot").classList.add("hidden");const app=$("#employee-app");app.classList.remove("hidden");app.innerHTML=`<button id="open-settings" class="settings-button" aria-label="الإعدادات"><i class="fa-solid fa-gear"></i></button><section class="employee-hero"><div class="profile-image">${employee.photoUrl?`<img src="${esc(employee.photoUrl)}" alt="">`:`<span>${initials(employee.fullName)}</span>`}</div><div><small>مرحباً بك</small><h1>${esc(employee.fullName)}</h1><p><i class="fa-regular fa-calendar-days"></i> ${schedule?`جدول دوام ${schedule.dayName}`:"لا يوجد جدول منشور"}</p></div></section><section class="today-card"><header><div><span>جدول الدوام</span><h2>${schedule?`${schedule.dayName} · ${schedule.dateKey}`:"بانتظار نشر الجدول"}</h2></div><i class="fa-regular fa-calendar-check"></i></header><div class="shifts">${items.length?items.map((item,index)=>shiftCard(item,index)).join(""):'<div class="no-shifts"><i class="fa-regular fa-calendar-xmark"></i><p>لا توجد فترات دوام منشورة لك حاليًا.</p></div>'}</div></section><section class="fingerprint-area"><button id="fingerprint-button"><i class="fa-solid fa-fingerprint"></i></button><h2>اضغط لتسجيل البصمة</h2><p id="fingerprint-status">يتم تسجيل وقت العملية مباشرة</p></section><nav class="bottom-nav"><button data-view="services"><i class="fa-solid fa-grip"></i><span>خدمات</span></button><button class="active"><i class="fa-solid fa-fingerprint"></i><span>البصمة</span></button><button data-view="notifications"><i class="fa-regular fa-bell"></i><span>إشعارات</span><em>${publishedSchedules.length}</em></button></nav>`;$("#open-settings").onclick=renderSettings;$("#fingerprint-button").onclick=recordAttendance;document.querySelector('[data-view="notifications"]').onclick=renderNotifications;}
function shiftCard(item,index){const branchNames={hawalli:"حولي",abu_al_hasaniya:"أبو الحصانية",yarmouk:"اليرموك"};return`<article class="shift-card"><b>الدوام ${index===0?"الأول":index===1?"الثاني":index+1}</b><div><span><i class="fa-regular fa-clock"></i><small>الوقت</small><strong>${formatTime(item.from)} — ${formatTime(item.to)}</strong></span><span><i class="fa-solid fa-location-dot"></i><small>الفرع</small><strong>${branchNames[item.branchId]||item.branchId}</strong></span><span><i class="fa-regular fa-clipboard"></i><small>المهام</small><strong>${item.tasks.map(esc).join(" + ")}</strong></span></div></article>`;}

async function recordAttendance(){const button=$("#fingerprint-button"),status=$("#fingerprint-status"),today=dateKey(new Date());button.disabled=true;status.textContent="جاري تسجيل البصمة...";try{const logsRef=ref(db,`organizations/default/attendance/${today}/${employee.id}`),snap=await get(logsRef),count=snap.exists()?Object.keys(snap.val()).length:0,type=count%2===0?"checkIn":"checkOut",entry=push(logsRef);await set(entry,{id:entry.key,employeeId:employee.id,type,timestamp:Date.now(),source:"employee-portal"});status.textContent=type==="checkIn"?"تم تسجيل الحضور بنجاح":"تم تسجيل الانصراف بنجاح";button.classList.add("success");showToast(status.textContent);}catch(error){status.textContent="تعذر تسجيل البصمة: "+error.message;}finally{button.disabled=false;setTimeout(()=>button.classList.remove("success"),1800);}}

function renderNotifications(){const app=$("#employee-app");app.innerHTML=`<div class="inner-page"><header><button id="back-home">→</button><div><small>التحديثات</small><h1>الإشعارات والجداول</h1></div></header><div class="notification-list">${publishedSchedules.length?publishedSchedules.slice().reverse().map(item=>`<article><i class="fa-regular fa-calendar-check"></i><div><b>تم نشر جدول ${esc(item.dayName)}</b><p>${esc(item.dateKey)} · افتح الصفحة الرئيسية لمشاهدة فتراتك.</p></div></article>`).join(""):'<div class="empty-state">لا توجد إشعارات حتى الآن.</div>'}</div></div>`;$("#back-home").onclick=renderHome;}

function renderSettings(){const alternates=employee.alternatePhones||[],relatives=employee.relatives||[];$("#employee-app").innerHTML=`<div class="inner-page settings-page"><header><button id="back-home">→</button><div><small>الملف الشخصي</small><h1>إعدادات بياناتي</h1><p>أكمل بياناتك الشخصية واحفظ التعديلات.</p></div></header><form id="settings-form"><section><h2>الصورة والبيانات الأساسية</h2><label class="settings-photo"><input id="settings-photo" type="file" accept="image/*"><span>${employee.photoUrl?`<img src="${esc(employee.photoUrl)}" alt="">`:`<i class="fa-solid fa-camera"></i>`}</span><b>تغيير الصورة</b></label><div class="settings-grid"><label>الاسم الكامل<input name="fullName" value="${esc(employee.fullName||"")}" required></label><label>الرقم المدني<input name="civilId" value="${esc(employee.civilId||"")}" inputmode="numeric" maxlength="12" required></label><label>الجنسية<select name="nationality"><option value="">اختر الجنسية</option>${countries.map(country=>`<option ${employee.nationality===country[0]?"selected":""}>${country[2]} ${country[0]}</option>`).join("")}</select></label><label>المسمى الوظيفي<input name="jobTitle" value="${esc(employee.jobTitle||"")}" required></label><label class="wide">جهة العمل<input name="workEntity" value="${esc(employee.workEntity||"")}" readonly></label></div></section><section><div class="settings-section-head"><h2>أرقام الهاتف</h2><button type="button" id="add-alt-phone">＋ رقم احتياطي</button></div><label>رقم الهاتف الشخصي${phoneField(employee.primaryPhone?.phone||employee.kuwaitPhone,employee.primaryPhone?.dialCode||"+965",0,"primary")}</label><div id="settings-alternates">${alternates.map((phone,index)=>phoneField(phone.phone,phone.dialCode,index,"alternate")).join("")}</div></section><section><div class="settings-section-head"><h2>أقرب الأشخاص</h2><button type="button" id="add-relative">＋ إضافة شخص</button></div><div id="settings-relatives">${relatives.map((person,index)=>relativeRow(person,index)).join("")}</div></section><section class="pin-settings"><h2>رمز دخول البصمة</h2><label>الرمز الجديد<input name="attendancePin" value="${esc(employee.attendancePin||currentPin)}" inputmode="numeric" minlength="4" maxlength="8" required></label><p>إذا كان الرمز مستخدمًا سيطلب منك النظام اختيار رمز آخر.</p></section><p id="settings-message"></p><button class="save-settings">حفظ بياناتي</button></form></div>`;bindSettingsEvents();}
function relativeRow(person={},index){return`<div class="relative-settings-row">${phoneField(person.phone,person.dialCode,index,"relative")}<input name="relation" value="${esc(person.relation||"")}" placeholder="نوع القرابة"><button type="button" data-remove-relative="${index}">×</button></div>`;}
function bindSettingsEvents(){bindNumeric($("#settings-form"));$("#back-home").onclick=renderHome;$("#settings-photo").onchange=event=>{const file=event.target.files[0];if(file)$(".settings-photo span").innerHTML=`<img src="${URL.createObjectURL(file)}" alt="">`;};$("#add-alt-phone").onclick=()=>{$("#settings-alternates").insertAdjacentHTML("beforeend",phoneField("","+965",$("#settings-alternates").children.length,"alternate"));bindSettingsEventsForRows();};$("#add-relative").onclick=()=>{$("#settings-relatives").insertAdjacentHTML("beforeend",relativeRow({},$("#settings-relatives").children.length));bindSettingsEventsForRows();};bindSettingsEventsForRows();$("#settings-form").onsubmit=saveSettings;}
function bindSettingsEventsForRows(){bindNumeric($("#settings-form"));document.querySelectorAll("[data-remove-phone]").forEach(button=>button.onclick=()=>button.parentElement.remove());document.querySelectorAll("[data-remove-relative]").forEach(button=>button.onclick=()=>button.parentElement.remove());}

async function saveSettings(event){event.preventDefault();const form=event.target,data=Object.fromEntries(new FormData(form)),newPin=onlyDigits(data.attendancePin),message=$("#settings-message");if(newPin.length<4||newPin.length>8){message.textContent="رمز البصمة يجب أن يكون من 4 إلى 8 أرقام.";return;}loading(true);let newPinReserved=false;try{if(newPin!==currentPin){const transaction=await runTransaction(ref(db,`organizations/default/attendancePins/${newPin}`),current=>current===null?employee.id:undefined,{applyLocally:false});if(!transaction.committed)throw new Error("رمز دخول البصمة مأخوذ، اختر رمزًا آخر.");newPinReserved=true;}let photoUrl=employee.photoUrl||"",file=$("#settings-photo").files[0];if(file){const target=storageRef(storage,`employee-photos/${employee.id}/${Date.now()}-${file.name}`);await uploadBytes(target,file);photoUrl=await getDownloadURL(target);}const alternatePhones=[...document.querySelectorAll("#settings-alternates .settings-phone-row")].map(row=>({dialCode:row.querySelector('select').value,phone:onlyDigits(row.querySelector('input').value)})).filter(item=>item.phone),relativeRows=[...document.querySelectorAll("#settings-relatives .relative-settings-row")],relatives=relativeRows.map(row=>({dialCode:row.querySelector('select').value,phone:onlyDigits(row.querySelector('.settings-phone-row input').value),relation:row.querySelector('[name="relation"]').value.trim()})).filter(item=>item.phone),primaryRow=document.querySelector('[name="primaryPhone"]').closest('.settings-phone-row'),changes={fullName:data.fullName.trim(),civilId:onlyDigits(data.civilId),nationality:data.nationality||"",jobTitle:data.jobTitle.trim(),primaryPhone:{dialCode:primaryRow.querySelector('select').value,phone:onlyDigits(primaryRow.querySelector('input').value)},alternatePhones,relatives,attendancePin:newPin,photoUrl,profileCompleted:true,profileUpdatedAt:Date.now()};await update(ref(db,`organizations/default/employees/${employee.id}`),changes);if(newPin!==currentPin){await remove(ref(db,`organizations/default/attendancePins/${currentPin}`));currentPin=newPin;sessionStorage.setItem("rakaezEmployeePin",newPin);}employee={...employee,...changes};showToast("تم حفظ بياناتك بنجاح");renderHome();}catch(error){if(newPinReserved)await remove(ref(db,`organizations/default/attendancePins/${newPin}`)).catch(()=>{});message.textContent=error.message;}finally{loading(false);}}

start();
